ALTER SESSION SET "_ORACLE_SCRIPT"=true;

CREATE USER EUNOIA IDENTIFIED BY EUNOIA
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, DBA TO EUNOIA;
GRANT CREATE VIEW, CREATE SYNONYM TO EUNOIA;
GRANT UNLIMITED TABLESPACE TO EUNOIA;